-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgwTgP4pTvk7g5Cgxs
slHpD9E+1LZvRSIzDjPyFze0HnygCgYIKoZIzj0DAQehRANCAARrJfnP+OSvVE3+
lz7d9UDJZFbpbxEHNBc5jVyNnq+xMvHEQMcUA5WI6VqawcaZ04oqp5Md/N5IOZbv
1ecCE0hU
-----END PRIVATE KEY-----